### ISSUE TITLE
[Movimentação Bancária] Erro ao fazer upload de arquivo

### ISSUE THREAD

**Issue by jorgeluizjr** [culturagovbr/docker-salic#7]
Ao tentar efetuar um upload de arquivo na funcionalidade de movimentação bancária está apresentando um erro "Não foi possível criar a pasta para armazenar o arquivo". Url : "salic.cultura.gov.br/movimentacaodeconta/upload".

**Comment by clebersantos** [comment]
Problema corrigido no próprio sistema.
